export const properties = {
  eyebrow: 'Featured properties',
  viewAllLabel: 'View all properties',
  viewAllTo: '/selling',
  items: [
    {
      slug: 'mt-eliza',
      status: 'For Sale',
      image: '/images/property-mt-eliza.jpg',
      imageAlt: 'Modern coastal home with garage at dusk',
      address: '12 The Boulevard',
      suburb: 'Mount Eliza',
      beds: 4,
      baths: 3,
      parking: 2,
      price: '$2,850,000',
    },
    {
      slug: 'highett',
      status: 'For Sale',
      image: '/images/property-highett.jpg',
      imageAlt: 'Designer dining and living room with feature lighting',
      address: '7/24 Woodville Street',
      suburb: 'Highett',
      beds: 3,
      baths: 2,
      parking: 2,
      price: '$1,495,000',
    },
    {
      slug: 'black-rock',
      status: 'For Lease',
      image: '/images/property-black-rock.jpg',
      imageAlt: 'Architectural home with infinity pool at twilight',
      address: '15 Beachview Road',
      suburb: 'Black Rock',
      beds: 4,
      baths: 2,
      parking: 2,
      price: '$1,200 per week',
    },
  ],
}
